
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-psql
spec:
  releaseName: devops-psql
  chart:
    spec:
      chart: postgresql-ha
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "12.8.2" # pin chart version, do not use "greater than" operators
  install:
    remediation:
      retries: -1
  interval: 24h0m0s