---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-base-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/AlexRodriguez09/base-infraestructure-nuamx.git
  secretRef:
    name: git-base-credentials