---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-base-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/nuamx/nuam-infraestructure-k8s-base.git
  secretRef:
    name: git-base-credentials