---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-base-initial
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/base-initial
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-base-source
  timeout: 3m0s
  wait: true