---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-base-stack-cr
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/base-stack-cr
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-base-source
  timeout: 3m0s
  wait: true
  dependsOn:
    - name: infrastructure-base-stack