---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustom-base-reposources
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./reposources
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-source
  timeout: 3m0s
  wait: true