---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustom-base-stack
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./base/infraestructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true