---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustom-base-infrastructure-devops
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./base/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
  dependsOn:
    - name: kustom-base-stack